### ISSUE TITLE
Module compiled does not match PHP compiled

### ISSUE THREAD

**Issue by shaneonabike** [kjdev/php-ext-zopfli#22]
Hey there,

So I'm trying to compile this on my server but it doesn't seem to jive. Presently, I have php7.3 installed and everything runs smoothly.

I am getting :

> PHP Warning:  PHP Startup: geos: Unable to initialize module
> Module compiled with module API=20170718
> PHP    compiled with module API=20180731
> These options need to match in Unknown on line 0

I read elsewhere that I needed to phpize7.3 so I tried that after doing a make distclean but that doesn't seem to help. Is there some other config that I need to do in order to make this all happy?

Thanks

**Comment by kjdev** [comment]
> PHP Warning: PHP Startup: geos: Unable to initialize module
> Module compiled with module API=20170718
> PHP compiled with module API=20180731
> These options need to match in Unknown on line 0

It looks like another `geos` extension, not a `zopifi` extension, is outputting the error.

**Comment by shaneonabike** [comment]
I am really sorry @kjdev! Originally, I was getting an error related to the .so not appearing and then resolved it. I think I just associated the other issues to the same plugin. THanks for pointing out my error
